{
 "title": "NOAA Water Data",
 "time": { "from": "2019-08-16T14:41:35.862Z", "to": "2019-09-18T22:27:54.179Z" },
 "panels": [
  {
   "title": "Coyote Creek PH Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "PH Level" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_pH",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "coyote_creek" }
     ]
    }
   ]
  },
  {
   "title": "Santa Monica PH Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "PH Level" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_pH",
     "select": [
      [
       { "params": [ "pH" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "santa_monica" }
     ]
    }
   ]
  },
  {
   "title": "Coyote Creek H2O Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_temperature",
     "query": "SELECT \"degrees\" FROM \"autogen\".\"h2o_temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "coyote_creek" }
     ]
    }
   ]
  },
  {
   "title": "Santa Monica H2O Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_temperature",
     "query": "SELECT \"degrees\" FROM \"autogen\".\"h2o_temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "degrees" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "santa_monica" }
     ]
    }
   ]
  },
  {
   "title": "Coyote Creek H2O Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Level (feet)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_feet",
     "select": [
      [
       { "params": [ "water_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "coyote_creek" }
     ]
    }
   ]
  },
  {
   "title": "Santa Monica H2O Level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Level (feet)" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "h2o_feet",
     "select": [
      [
       { "params": [ "water_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "location", "operator": "=", "value": "santa_monica" }
     ]
    }
   ]
  }
 ]
}